// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HallGuildMessage.proto

package info.xiaomo.server.shared.protocol.hall.guild;

public interface GuildApprovalRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GuildApprovalRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *消息id
   * </pre>
   *
   * <code>optional .MID mid = 1 [default = GuildApprovalReq];</code>
   * @return Whether the mid field is set.
   */
  boolean hasMid();
  /**
   * <pre>
   *消息id
   * </pre>
   *
   * <code>optional .MID mid = 1 [default = GuildApprovalReq];</code>
   * @return The mid.
   */
  info.xiaomo.server.shared.protocol.Mid.MID getMid();

  /**
   * <pre>
   *被操作的角色
   * </pre>
   *
   * <code>optional int64 roleId = 2;</code>
   * @return Whether the roleId field is set.
   */
  boolean hasRoleId();
  /**
   * <pre>
   *被操作的角色
   * </pre>
   *
   * <code>optional int64 roleId = 2;</code>
   * @return The roleId.
   */
  long getRoleId();

  /**
   * <pre>
   *操作类型 0批准加入、1踢人、2解散
   * </pre>
   *
   * <code>required int32 type = 3;</code>
   * @return Whether the type field is set.
   */
  boolean hasType();
  /**
   * <pre>
   *操作类型 0批准加入、1踢人、2解散
   * </pre>
   *
   * <code>required int32 type = 3;</code>
   * @return The type.
   */
  int getType();
}
