// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HallGuildMessage.proto

package info.xiaomo.server.shared.protocol.hall.guild;

public interface GuildInfoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GuildInfoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *消息id
   * </pre>
   *
   * <code>optional .MID mid = 1 [default = GuildInfoRes];</code>
   * @return Whether the mid field is set.
   */
  boolean hasMid();
  /**
   * <pre>
   *消息id
   * </pre>
   *
   * <code>optional .MID mid = 1 [default = GuildInfoRes];</code>
   * @return The mid.
   */
  info.xiaomo.server.shared.protocol.Mid.MID getMid();

  /**
   * <pre>
   *帮会信息 
   * </pre>
   *
   * <code>optional .GuildInfo guildInfo = 2;</code>
   * @return Whether the guildInfo field is set.
   */
  boolean hasGuildInfo();
  /**
   * <pre>
   *帮会信息 
   * </pre>
   *
   * <code>optional .GuildInfo guildInfo = 2;</code>
   * @return The guildInfo.
   */
  info.xiaomo.server.shared.protocol.hall.guild.GuildInfo getGuildInfo();
  /**
   * <pre>
   *帮会信息 
   * </pre>
   *
   * <code>optional .GuildInfo guildInfo = 2;</code>
   */
  info.xiaomo.server.shared.protocol.hall.guild.GuildInfoOrBuilder getGuildInfoOrBuilder();
}
