// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BydrFightMessage.proto

package info.xiaomo.server.shared.protocol.gameserver.fight;

/**
 * <pre>
 *伤害结果
 * </pre>
 *
 * Protobuf type {@code FireResultResponse}
 */
public final class FireResultResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:FireResultResponse)
    FireResultResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FireResultResponse.newBuilder() to construct.
  private FireResultResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FireResultResponse() {
    mid_ = 20018;
    dieFishId_ = emptyLongList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FireResultResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FireResultResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();
              @SuppressWarnings("deprecation")
            info.xiaomo.server.shared.protocol.Mid.MID value = info.xiaomo.server.shared.protocol.Mid.MID.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(1, rawValue);
            } else {
              bitField0_ |= 0x00000001;
              mid_ = rawValue;
            }
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            rid_ = input.readInt64();
            break;
          }
          case 24: {
            if (!((mutable_bitField0_ & 0x00000004) != 0)) {
              dieFishId_ = newLongList();
              mutable_bitField0_ |= 0x00000004;
            }
            dieFishId_.addLong(input.readInt64());
            break;
          }
          case 26: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000004) != 0) && input.getBytesUntilLimit() > 0) {
              dieFishId_ = newLongList();
              mutable_bitField0_ |= 0x00000004;
            }
            while (input.getBytesUntilLimit() > 0) {
              dieFishId_.addLong(input.readInt64());
            }
            input.popLimit(limit);
            break;
          }
          case 32: {
            bitField0_ |= 0x00000004;
            gold_ = input.readInt64();
            break;
          }
          case 40: {
            bitField0_ |= 0x00000008;
            multiple_ = input.readInt32();
            break;
          }
          case 48: {
            bitField0_ |= 0x00000010;
            specialFishId_ = input.readInt64();
            break;
          }
          case 56: {
            bitField0_ |= 0x00000020;
            accumulateGold_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) != 0)) {
        dieFishId_.makeImmutable(); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return info.xiaomo.server.shared.protocol.gameserver.fight.BydrFightMessage.internal_static_FireResultResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return info.xiaomo.server.shared.protocol.gameserver.fight.BydrFightMessage.internal_static_FireResultResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            info.xiaomo.server.shared.protocol.gameserver.fight.FireResultResponse.class, info.xiaomo.server.shared.protocol.gameserver.fight.FireResultResponse.Builder.class);
  }

  private int bitField0_;
  public static final int MID_FIELD_NUMBER = 1;
  private int mid_;
  /**
   * <pre>
   *消息id
   * </pre>
   *
   * <code>optional .MID mid = 1 [default = FireResultRes];</code>
   * @return Whether the mid field is set.
   */
  @java.lang.Override public boolean hasMid() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   *消息id
   * </pre>
   *
   * <code>optional .MID mid = 1 [default = FireResultRes];</code>
   * @return The mid.
   */
  @java.lang.Override public info.xiaomo.server.shared.protocol.Mid.MID getMid() {
    @SuppressWarnings("deprecation")
    info.xiaomo.server.shared.protocol.Mid.MID result = info.xiaomo.server.shared.protocol.Mid.MID.valueOf(mid_);
    return result == null ? info.xiaomo.server.shared.protocol.Mid.MID.FireResultRes : result;
  }

  public static final int RID_FIELD_NUMBER = 2;
  private long rid_;
  /**
   * <pre>
   *开炮的玩家ID
   * </pre>
   *
   * <code>optional int64 rid = 2;</code>
   * @return Whether the rid field is set.
   */
  @java.lang.Override
  public boolean hasRid() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   *开炮的玩家ID
   * </pre>
   *
   * <code>optional int64 rid = 2;</code>
   * @return The rid.
   */
  @java.lang.Override
  public long getRid() {
    return rid_;
  }

  public static final int DIEFISHID_FIELD_NUMBER = 3;
  private com.google.protobuf.Internal.LongList dieFishId_;
  /**
   * <pre>
   *死亡获分的鱼ID
   * </pre>
   *
   * <code>repeated int64 dieFishId = 3;</code>
   * @return A list containing the dieFishId.
   */
  @java.lang.Override
  public java.util.List<java.lang.Long>
      getDieFishIdList() {
    return dieFishId_;
  }
  /**
   * <pre>
   *死亡获分的鱼ID
   * </pre>
   *
   * <code>repeated int64 dieFishId = 3;</code>
   * @return The count of dieFishId.
   */
  public int getDieFishIdCount() {
    return dieFishId_.size();
  }
  /**
   * <pre>
   *死亡获分的鱼ID
   * </pre>
   *
   * <code>repeated int64 dieFishId = 3;</code>
   * @param index The index of the element to return.
   * @return The dieFishId at the given index.
   */
  public long getDieFishId(int index) {
    return dieFishId_.getLong(index);
  }

  public static final int GOLD_FIELD_NUMBER = 4;
  private long gold_;
  /**
   * <pre>
   *玩家当前金币
   * </pre>
   *
   * <code>optional int64 gold = 4;</code>
   * @return Whether the gold field is set.
   */
  @java.lang.Override
  public boolean hasGold() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   *玩家当前金币
   * </pre>
   *
   * <code>optional int64 gold = 4;</code>
   * @return The gold.
   */
  @java.lang.Override
  public long getGold() {
    return gold_;
  }

  public static final int MULTIPLE_FIELD_NUMBER = 5;
  private int multiple_;
  /**
   * <pre>
   *特殊鱼计算的倍数 0普通鱼 -1获得累积奖
   * </pre>
   *
   * <code>optional int32 multiple = 5;</code>
   * @return Whether the multiple field is set.
   */
  @java.lang.Override
  public boolean hasMultiple() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <pre>
   *特殊鱼计算的倍数 0普通鱼 -1获得累积奖
   * </pre>
   *
   * <code>optional int32 multiple = 5;</code>
   * @return The multiple.
   */
  @java.lang.Override
  public int getMultiple() {
    return multiple_;
  }

  public static final int SPECIALFISHID_FIELD_NUMBER = 6;
  private long specialFishId_;
  /**
   * <pre>
   *特殊鱼ID
   * </pre>
   *
   * <code>optional int64 specialFishId = 6;</code>
   * @return Whether the specialFishId field is set.
   */
  @java.lang.Override
  public boolean hasSpecialFishId() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <pre>
   *特殊鱼ID
   * </pre>
   *
   * <code>optional int64 specialFishId = 6;</code>
   * @return The specialFishId.
   */
  @java.lang.Override
  public long getSpecialFishId() {
    return specialFishId_;
  }

  public static final int ACCUMULATEGOLD_FIELD_NUMBER = 7;
  private long accumulateGold_;
  /**
   * <pre>
   *累积池金币
   * </pre>
   *
   * <code>optional int64 accumulateGold = 7;</code>
   * @return Whether the accumulateGold field is set.
   */
  @java.lang.Override
  public boolean hasAccumulateGold() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <pre>
   *累积池金币
   * </pre>
   *
   * <code>optional int64 accumulateGold = 7;</code>
   * @return The accumulateGold.
   */
  @java.lang.Override
  public long getAccumulateGold() {
    return accumulateGold_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeEnum(1, mid_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt64(2, rid_);
    }
    for (int i = 0; i < dieFishId_.size(); i++) {
      output.writeInt64(3, dieFishId_.getLong(i));
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeInt64(4, gold_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeInt32(5, multiple_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeInt64(6, specialFishId_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeInt64(7, accumulateGold_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, mid_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, rid_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < dieFishId_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(dieFishId_.getLong(i));
      }
      size += dataSize;
      size += 1 * getDieFishIdList().size();
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, gold_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, multiple_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, specialFishId_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, accumulateGold_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof info.xiaomo.server.shared.protocol.gameserver.fight.FireResultResponse)) {
      return super.equals(obj);
    }
    info.xiaomo.server.shared.protocol.gameserver.fight.FireResultResponse other = (info.xiaomo.server.shared.protocol.gameserver.fight.FireResultResponse) obj;

    if (hasMid() != other.hasMid()) return false;
    if (hasMid()) {
      if (mid_ != other.mid_) return false;
    }
    if (hasRid() != other.hasRid()) return false;
    if (hasRid()) {
      if (getRid()
          != other.getRid()) return false;
    }
    if (!getDieFishIdList()
        .equals(other.getDieFishIdList())) return false;
    if (hasGold() != other.hasGold()) return false;
    if (hasGold()) {
      if (getGold()
          != other.getGold()) return false;
    }
    if (hasMultiple() != other.hasMultiple()) return false;
    if (hasMultiple()) {
      if (getMultiple()
          != other.getMultiple()) return false;
    }
    if (hasSpecialFishId() != other.hasSpecialFishId()) return false;
    if (hasSpecialFishId()) {
      if (getSpecialFishId()
          != other.getSpecialFishId()) return false;
    }
    if (hasAccumulateGold() != other.hasAccumulateGold()) return false;
    if (hasAccumulateGold()) {
      if (getAccumulateGold()
          != other.getAccumulateGold()) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasMid()) {
      hash = (37 * hash) + MID_FIELD_NUMBER;
      hash = (53 * hash) + mid_;
    }
    if (hasRid()) {
      hash = (37 * hash) + RID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRid());
    }
    if (getDieFishIdCount() > 0) {
      hash = (37 * hash) + DIEFISHID_FIELD_NUMBER;
      hash = (53 * hash) + getDieFishIdList().hashCode();
    }
    if (hasGold()) {
      hash = (37 * hash) + GOLD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getGold());
    }
    if (hasMultiple()) {
      hash = (37 * hash) + MULTIPLE_FIELD_NUMBER;
      hash = (53 * hash) + getMultiple();
    }
    if (hasSpecialFishId()) {
      hash = (37 * hash) + SPECIALFISHID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSpecialFishId());
    }
    if (hasAccumulateGold()) {
      hash = (37 * hash) + ACCUMULATEGOLD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getAccumulateGold());
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static info.xiaomo.server.shared.protocol.gameserver.fight.FireResultResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static info.xiaomo.server.shared.protocol.gameserver.fight.FireResultResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static info.xiaomo.server.shared.protocol.gameserver.fight.FireResultResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static info.xiaomo.server.shared.protocol.gameserver.fight.FireResultResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static info.xiaomo.server.shared.protocol.gameserver.fight.FireResultResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static info.xiaomo.server.shared.protocol.gameserver.fight.FireResultResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static info.xiaomo.server.shared.protocol.gameserver.fight.FireResultResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static info.xiaomo.server.shared.protocol.gameserver.fight.FireResultResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static info.xiaomo.server.shared.protocol.gameserver.fight.FireResultResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static info.xiaomo.server.shared.protocol.gameserver.fight.FireResultResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static info.xiaomo.server.shared.protocol.gameserver.fight.FireResultResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static info.xiaomo.server.shared.protocol.gameserver.fight.FireResultResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(info.xiaomo.server.shared.protocol.gameserver.fight.FireResultResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *伤害结果
   * </pre>
   *
   * Protobuf type {@code FireResultResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:FireResultResponse)
      info.xiaomo.server.shared.protocol.gameserver.fight.FireResultResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return info.xiaomo.server.shared.protocol.gameserver.fight.BydrFightMessage.internal_static_FireResultResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return info.xiaomo.server.shared.protocol.gameserver.fight.BydrFightMessage.internal_static_FireResultResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              info.xiaomo.server.shared.protocol.gameserver.fight.FireResultResponse.class, info.xiaomo.server.shared.protocol.gameserver.fight.FireResultResponse.Builder.class);
    }

    // Construct using info.xiaomo.server.shared.protocol.gameserver.fight.FireResultResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      mid_ = 20018;
      bitField0_ = (bitField0_ & ~0x00000001);
      rid_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000002);
      dieFishId_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000004);
      gold_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000008);
      multiple_ = 0;
      bitField0_ = (bitField0_ & ~0x00000010);
      specialFishId_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000020);
      accumulateGold_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000040);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return info.xiaomo.server.shared.protocol.gameserver.fight.BydrFightMessage.internal_static_FireResultResponse_descriptor;
    }

    @java.lang.Override
    public info.xiaomo.server.shared.protocol.gameserver.fight.FireResultResponse getDefaultInstanceForType() {
      return info.xiaomo.server.shared.protocol.gameserver.fight.FireResultResponse.getDefaultInstance();
    }

    @java.lang.Override
    public info.xiaomo.server.shared.protocol.gameserver.fight.FireResultResponse build() {
      info.xiaomo.server.shared.protocol.gameserver.fight.FireResultResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public info.xiaomo.server.shared.protocol.gameserver.fight.FireResultResponse buildPartial() {
      info.xiaomo.server.shared.protocol.gameserver.fight.FireResultResponse result = new info.xiaomo.server.shared.protocol.gameserver.fight.FireResultResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.mid_ = mid_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.rid_ = rid_;
        to_bitField0_ |= 0x00000002;
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        dieFishId_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.dieFishId_ = dieFishId_;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.gold_ = gold_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.multiple_ = multiple_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.specialFishId_ = specialFishId_;
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.accumulateGold_ = accumulateGold_;
        to_bitField0_ |= 0x00000020;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof info.xiaomo.server.shared.protocol.gameserver.fight.FireResultResponse) {
        return mergeFrom((info.xiaomo.server.shared.protocol.gameserver.fight.FireResultResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(info.xiaomo.server.shared.protocol.gameserver.fight.FireResultResponse other) {
      if (other == info.xiaomo.server.shared.protocol.gameserver.fight.FireResultResponse.getDefaultInstance()) return this;
      if (other.hasMid()) {
        setMid(other.getMid());
      }
      if (other.hasRid()) {
        setRid(other.getRid());
      }
      if (!other.dieFishId_.isEmpty()) {
        if (dieFishId_.isEmpty()) {
          dieFishId_ = other.dieFishId_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureDieFishIdIsMutable();
          dieFishId_.addAll(other.dieFishId_);
        }
        onChanged();
      }
      if (other.hasGold()) {
        setGold(other.getGold());
      }
      if (other.hasMultiple()) {
        setMultiple(other.getMultiple());
      }
      if (other.hasSpecialFishId()) {
        setSpecialFishId(other.getSpecialFishId());
      }
      if (other.hasAccumulateGold()) {
        setAccumulateGold(other.getAccumulateGold());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      info.xiaomo.server.shared.protocol.gameserver.fight.FireResultResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (info.xiaomo.server.shared.protocol.gameserver.fight.FireResultResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int mid_ = 20018;
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>optional .MID mid = 1 [default = FireResultRes];</code>
     * @return Whether the mid field is set.
     */
    @java.lang.Override public boolean hasMid() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>optional .MID mid = 1 [default = FireResultRes];</code>
     * @return The mid.
     */
    @java.lang.Override
    public info.xiaomo.server.shared.protocol.Mid.MID getMid() {
      @SuppressWarnings("deprecation")
      info.xiaomo.server.shared.protocol.Mid.MID result = info.xiaomo.server.shared.protocol.Mid.MID.valueOf(mid_);
      return result == null ? info.xiaomo.server.shared.protocol.Mid.MID.FireResultRes : result;
    }
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>optional .MID mid = 1 [default = FireResultRes];</code>
     * @param value The mid to set.
     * @return This builder for chaining.
     */
    public Builder setMid(info.xiaomo.server.shared.protocol.Mid.MID value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      mid_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>optional .MID mid = 1 [default = FireResultRes];</code>
     * @return This builder for chaining.
     */
    public Builder clearMid() {
      bitField0_ = (bitField0_ & ~0x00000001);
      mid_ = 20018;
      onChanged();
      return this;
    }

    private long rid_ ;
    /**
     * <pre>
     *开炮的玩家ID
     * </pre>
     *
     * <code>optional int64 rid = 2;</code>
     * @return Whether the rid field is set.
     */
    @java.lang.Override
    public boolean hasRid() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     *开炮的玩家ID
     * </pre>
     *
     * <code>optional int64 rid = 2;</code>
     * @return The rid.
     */
    @java.lang.Override
    public long getRid() {
      return rid_;
    }
    /**
     * <pre>
     *开炮的玩家ID
     * </pre>
     *
     * <code>optional int64 rid = 2;</code>
     * @param value The rid to set.
     * @return This builder for chaining.
     */
    public Builder setRid(long value) {
      bitField0_ |= 0x00000002;
      rid_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *开炮的玩家ID
     * </pre>
     *
     * <code>optional int64 rid = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRid() {
      bitField0_ = (bitField0_ & ~0x00000002);
      rid_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.LongList dieFishId_ = emptyLongList();
    private void ensureDieFishIdIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        dieFishId_ = mutableCopy(dieFishId_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <pre>
     *死亡获分的鱼ID
     * </pre>
     *
     * <code>repeated int64 dieFishId = 3;</code>
     * @return A list containing the dieFishId.
     */
    public java.util.List<java.lang.Long>
        getDieFishIdList() {
      return ((bitField0_ & 0x00000004) != 0) ?
               java.util.Collections.unmodifiableList(dieFishId_) : dieFishId_;
    }
    /**
     * <pre>
     *死亡获分的鱼ID
     * </pre>
     *
     * <code>repeated int64 dieFishId = 3;</code>
     * @return The count of dieFishId.
     */
    public int getDieFishIdCount() {
      return dieFishId_.size();
    }
    /**
     * <pre>
     *死亡获分的鱼ID
     * </pre>
     *
     * <code>repeated int64 dieFishId = 3;</code>
     * @param index The index of the element to return.
     * @return The dieFishId at the given index.
     */
    public long getDieFishId(int index) {
      return dieFishId_.getLong(index);
    }
    /**
     * <pre>
     *死亡获分的鱼ID
     * </pre>
     *
     * <code>repeated int64 dieFishId = 3;</code>
     * @param index The index to set the value at.
     * @param value The dieFishId to set.
     * @return This builder for chaining.
     */
    public Builder setDieFishId(
        int index, long value) {
      ensureDieFishIdIsMutable();
      dieFishId_.setLong(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *死亡获分的鱼ID
     * </pre>
     *
     * <code>repeated int64 dieFishId = 3;</code>
     * @param value The dieFishId to add.
     * @return This builder for chaining.
     */
    public Builder addDieFishId(long value) {
      ensureDieFishIdIsMutable();
      dieFishId_.addLong(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *死亡获分的鱼ID
     * </pre>
     *
     * <code>repeated int64 dieFishId = 3;</code>
     * @param values The dieFishId to add.
     * @return This builder for chaining.
     */
    public Builder addAllDieFishId(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureDieFishIdIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, dieFishId_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *死亡获分的鱼ID
     * </pre>
     *
     * <code>repeated int64 dieFishId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDieFishId() {
      dieFishId_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }

    private long gold_ ;
    /**
     * <pre>
     *玩家当前金币
     * </pre>
     *
     * <code>optional int64 gold = 4;</code>
     * @return Whether the gold field is set.
     */
    @java.lang.Override
    public boolean hasGold() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     *玩家当前金币
     * </pre>
     *
     * <code>optional int64 gold = 4;</code>
     * @return The gold.
     */
    @java.lang.Override
    public long getGold() {
      return gold_;
    }
    /**
     * <pre>
     *玩家当前金币
     * </pre>
     *
     * <code>optional int64 gold = 4;</code>
     * @param value The gold to set.
     * @return This builder for chaining.
     */
    public Builder setGold(long value) {
      bitField0_ |= 0x00000008;
      gold_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *玩家当前金币
     * </pre>
     *
     * <code>optional int64 gold = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearGold() {
      bitField0_ = (bitField0_ & ~0x00000008);
      gold_ = 0L;
      onChanged();
      return this;
    }

    private int multiple_ ;
    /**
     * <pre>
     *特殊鱼计算的倍数 0普通鱼 -1获得累积奖
     * </pre>
     *
     * <code>optional int32 multiple = 5;</code>
     * @return Whether the multiple field is set.
     */
    @java.lang.Override
    public boolean hasMultiple() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     *特殊鱼计算的倍数 0普通鱼 -1获得累积奖
     * </pre>
     *
     * <code>optional int32 multiple = 5;</code>
     * @return The multiple.
     */
    @java.lang.Override
    public int getMultiple() {
      return multiple_;
    }
    /**
     * <pre>
     *特殊鱼计算的倍数 0普通鱼 -1获得累积奖
     * </pre>
     *
     * <code>optional int32 multiple = 5;</code>
     * @param value The multiple to set.
     * @return This builder for chaining.
     */
    public Builder setMultiple(int value) {
      bitField0_ |= 0x00000010;
      multiple_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *特殊鱼计算的倍数 0普通鱼 -1获得累积奖
     * </pre>
     *
     * <code>optional int32 multiple = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearMultiple() {
      bitField0_ = (bitField0_ & ~0x00000010);
      multiple_ = 0;
      onChanged();
      return this;
    }

    private long specialFishId_ ;
    /**
     * <pre>
     *特殊鱼ID
     * </pre>
     *
     * <code>optional int64 specialFishId = 6;</code>
     * @return Whether the specialFishId field is set.
     */
    @java.lang.Override
    public boolean hasSpecialFishId() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     *特殊鱼ID
     * </pre>
     *
     * <code>optional int64 specialFishId = 6;</code>
     * @return The specialFishId.
     */
    @java.lang.Override
    public long getSpecialFishId() {
      return specialFishId_;
    }
    /**
     * <pre>
     *特殊鱼ID
     * </pre>
     *
     * <code>optional int64 specialFishId = 6;</code>
     * @param value The specialFishId to set.
     * @return This builder for chaining.
     */
    public Builder setSpecialFishId(long value) {
      bitField0_ |= 0x00000020;
      specialFishId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *特殊鱼ID
     * </pre>
     *
     * <code>optional int64 specialFishId = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSpecialFishId() {
      bitField0_ = (bitField0_ & ~0x00000020);
      specialFishId_ = 0L;
      onChanged();
      return this;
    }

    private long accumulateGold_ ;
    /**
     * <pre>
     *累积池金币
     * </pre>
     *
     * <code>optional int64 accumulateGold = 7;</code>
     * @return Whether the accumulateGold field is set.
     */
    @java.lang.Override
    public boolean hasAccumulateGold() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <pre>
     *累积池金币
     * </pre>
     *
     * <code>optional int64 accumulateGold = 7;</code>
     * @return The accumulateGold.
     */
    @java.lang.Override
    public long getAccumulateGold() {
      return accumulateGold_;
    }
    /**
     * <pre>
     *累积池金币
     * </pre>
     *
     * <code>optional int64 accumulateGold = 7;</code>
     * @param value The accumulateGold to set.
     * @return This builder for chaining.
     */
    public Builder setAccumulateGold(long value) {
      bitField0_ |= 0x00000040;
      accumulateGold_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *累积池金币
     * </pre>
     *
     * <code>optional int64 accumulateGold = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearAccumulateGold() {
      bitField0_ = (bitField0_ & ~0x00000040);
      accumulateGold_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:FireResultResponse)
  }

  // @@protoc_insertion_point(class_scope:FireResultResponse)
  private static final info.xiaomo.server.shared.protocol.gameserver.fight.FireResultResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new info.xiaomo.server.shared.protocol.gameserver.fight.FireResultResponse();
  }

  public static info.xiaomo.server.shared.protocol.gameserver.fight.FireResultResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<FireResultResponse>
      PARSER = new com.google.protobuf.AbstractParser<FireResultResponse>() {
    @java.lang.Override
    public FireResultResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FireResultResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FireResultResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FireResultResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public info.xiaomo.server.shared.protocol.gameserver.fight.FireResultResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

