// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SystemMessage.proto

package info.xiaomo.server.shared.protocol.system;

public interface HeartResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HeartResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *消息id
   * </pre>
   *
   * <code>optional .MID mid = 1 [default = HeartRes];</code>
   * @return Whether the mid field is set.
   */
  boolean hasMid();
  /**
   * <pre>
   *消息id
   * </pre>
   *
   * <code>optional .MID mid = 1 [default = HeartRes];</code>
   * @return The mid.
   */
  info.xiaomo.server.shared.protocol.Mid.MID getMid();

  /**
   * <pre>
   *服务器时间
   * </pre>
   *
   * <code>optional int64 serverTime = 2;</code>
   * @return Whether the serverTime field is set.
   */
  boolean hasServerTime();
  /**
   * <pre>
   *服务器时间
   * </pre>
   *
   * <code>optional int64 serverTime = 2;</code>
   * @return The serverTime.
   */
  long getServerTime();
}
