// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SystemMessage.proto

package info.xiaomo.server.shared.protocol.system;

public final class SystemMessage {
  private SystemMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SystemErrorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SystemErrorResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeartRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeartRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeartResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeartResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UdpConnectRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UdpConnectRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UdpConnectResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UdpConnectResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023SystemMessage.proto\032\tMid.proto\"i\n\023Syst" +
      "emErrorResponse\022!\n\003mid\030\001 \001(\0162\004.MID:\016Syst" +
      "emErrorRes\022\"\n\terrorCode\030\002 \001(\0162\017.SystemEr" +
      "roCode\022\013\n\003msg\030\003 \001(\t\"+\n\014HeartRequest\022\033\n\003m" +
      "id\030\001 \001(\0162\004.MID:\010HeartReq\"@\n\rHeartRespons" +
      "e\022\033\n\003mid\030\001 \001(\0162\004.MID:\010HeartRes\022\022\n\nserver" +
      "Time\030\002 \001(\003\"U\n\021UdpConnectRequest\022 \n\003mid\030\001" +
      " \001(\0162\004.MID:\rUdpConnectReq\022\021\n\tsessionId\030\002" +
      " \001(\003\022\013\n\003rid\030\003 \001(\003\"F\n\022UdpConnectResponse\022" +
      " \n\003mid\030\001 \001(\0162\004.MID:\rUdpConnectRes\022\016\n\006res" +
      "ult\030\002 \001(\005*C\n\016SystemErroCode\022\017\n\013HallNotFi" +
      "nd\020\001\022\017\n\013GameNotFind\020\002\022\017\n\013ConectReset\020\003B-" +
      "\n)info.xiaomo.server.shared.protocol.sys" +
      "temP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          info.xiaomo.server.shared.protocol.Mid.getDescriptor(),
        });
    internal_static_SystemErrorResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SystemErrorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SystemErrorResponse_descriptor,
        new java.lang.String[] { "Mid", "ErrorCode", "Msg", });
    internal_static_HeartRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HeartRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeartRequest_descriptor,
        new java.lang.String[] { "Mid", });
    internal_static_HeartResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_HeartResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeartResponse_descriptor,
        new java.lang.String[] { "Mid", "ServerTime", });
    internal_static_UdpConnectRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_UdpConnectRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UdpConnectRequest_descriptor,
        new java.lang.String[] { "Mid", "SessionId", "Rid", });
    internal_static_UdpConnectResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_UdpConnectResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UdpConnectResponse_descriptor,
        new java.lang.String[] { "Mid", "Result", });
    info.xiaomo.server.shared.protocol.Mid.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
