// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HallLoginMessage.proto

package info.xiaomo.server.shared.protocol.hall.login;

public final class HallLoginMessage {
  private HallLoginMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QuitRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_QuitRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QuitResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_QuitResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginSubGameRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginSubGameRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginSubGameResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginSubGameResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QuitSubGameRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_QuitSubGameRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QuitSubGameResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_QuitSubGameResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026HallLoginMessage.proto\032\tMid.proto\"\255\001\n\014" +
      "LoginRequest\022\033\n\003mid\030\001 \001(\0162\004.MID:\010LoginRe" +
      "q\022\017\n\007account\030\002 \001(\t\022\020\n\010password\030\003 \001(\t\022\035\n\t" +
      "loginType\030\004 \001(\0162\n.LoginType\022\021\n\tsessionId" +
      "\030\005 \001(\003\022\016\n\006gateId\030\006 \001(\005\022\n\n\002ip\030\007 \001(\t\022\017\n\007ve" +
      "rsion\030\010 \001(\t\"g\n\rLoginResponse\022\033\n\003mid\030\001 \001(" +
      "\0162\004.MID:\010LoginRes\022\014\n\004isOk\030\002 \001(\010\022\013\n\003uid\030\003" +
      " \001(\003\022\013\n\003rid\030\004 \001(\003\022\021\n\tsessionId\030\005 \001(\003\"6\n\013" +
      "QuitRequest\022\032\n\003mid\030\001 \001(\0162\004.MID:\007QuitReq\022" +
      "\013\n\003rid\030\002 \001(\003\":\n\014QuitResponse\022\032\n\003mid\030\001 \001(" +
      "\0162\004.MID:\007QuitRes\022\016\n\006result\030\002 \001(\005\"f\n\023Logi" +
      "nSubGameRequest\022\"\n\003mid\030\001 \001(\0162\004.MID:\017Logi" +
      "nSubGameReq\022\013\n\003rid\030\002 \002(\003\022\014\n\004type\030\003 \001(\005\022\020" +
      "\n\010gameType\030\004 \001(\005\"J\n\024LoginSubGameResponse" +
      "\022\"\n\003mid\030\001 \001(\0162\004.MID:\017LoginSubGameRes\022\016\n\006" +
      "result\030\002 \001(\005\"D\n\022QuitSubGameRequest\022!\n\003mi" +
      "d\030\001 \001(\0162\004.MID:\016QuitSubGameReq\022\013\n\003rid\030\002 \001" +
      "(\003\"H\n\023QuitSubGameResponse\022!\n\003mid\030\001 \001(\0162\004" +
      ".MID:\016QuitSubGameRes\022\016\n\006result\030\002 \001(\005*\030\n\t" +
      "LoginType\022\013\n\007ACCOUNT\020\001B1\n-info.xiaomo.se" +
      "rver.shared.protocol.hall.loginP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          info.xiaomo.server.shared.protocol.Mid.getDescriptor(),
        });
    internal_static_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginRequest_descriptor,
        new java.lang.String[] { "Mid", "Account", "Password", "LoginType", "SessionId", "GateId", "Ip", "Version", });
    internal_static_LoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_LoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginResponse_descriptor,
        new java.lang.String[] { "Mid", "IsOk", "Uid", "Rid", "SessionId", });
    internal_static_QuitRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_QuitRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_QuitRequest_descriptor,
        new java.lang.String[] { "Mid", "Rid", });
    internal_static_QuitResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_QuitResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_QuitResponse_descriptor,
        new java.lang.String[] { "Mid", "Result", });
    internal_static_LoginSubGameRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_LoginSubGameRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginSubGameRequest_descriptor,
        new java.lang.String[] { "Mid", "Rid", "Type", "GameType", });
    internal_static_LoginSubGameResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_LoginSubGameResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginSubGameResponse_descriptor,
        new java.lang.String[] { "Mid", "Result", });
    internal_static_QuitSubGameRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_QuitSubGameRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_QuitSubGameRequest_descriptor,
        new java.lang.String[] { "Mid", "Rid", });
    internal_static_QuitSubGameResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_QuitSubGameResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_QuitSubGameResponse_descriptor,
        new java.lang.String[] { "Mid", "Result", });
    info.xiaomo.server.shared.protocol.Mid.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
