// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HallLoginMessage.proto

package info.xiaomo.server.shared.protocol.hall.login;

public interface LoginResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LoginResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *消息id
   * </pre>
   *
   * <code>optional .MID mid = 1 [default = LoginRes];</code>
   * @return Whether the mid field is set.
   */
  boolean hasMid();
  /**
   * <pre>
   *消息id
   * </pre>
   *
   * <code>optional .MID mid = 1 [default = LoginRes];</code>
   * @return The mid.
   */
  info.xiaomo.server.shared.protocol.Mid.MID getMid();

  /**
   * <pre>
   *请求是否发送成功
   * </pre>
   *
   * <code>optional bool isOk = 2;</code>
   * @return Whether the isOk field is set.
   */
  boolean hasIsOk();
  /**
   * <pre>
   *请求是否发送成功
   * </pre>
   *
   * <code>optional bool isOk = 2;</code>
   * @return The isOk.
   */
  boolean getIsOk();

  /**
   * <pre>
   *用户id
   * </pre>
   *
   * <code>optional int64 uid = 3;</code>
   * @return Whether the uid field is set.
   */
  boolean hasUid();
  /**
   * <pre>
   *用户id
   * </pre>
   *
   * <code>optional int64 uid = 3;</code>
   * @return The uid.
   */
  long getUid();

  /**
   * <pre>
   *角色ID
   * </pre>
   *
   * <code>optional int64 rid = 4;</code>
   * @return Whether the rid field is set.
   */
  boolean hasRid();
  /**
   * <pre>
   *角色ID
   * </pre>
   *
   * <code>optional int64 rid = 4;</code>
   * @return The rid.
   */
  long getRid();

  /**
   * <pre>
   *会话ID
   * </pre>
   *
   * <code>optional int64 sessionId = 5;</code>
   * @return Whether the sessionId field is set.
   */
  boolean hasSessionId();
  /**
   * <pre>
   *会话ID
   * </pre>
   *
   * <code>optional int64 sessionId = 5;</code>
   * @return The sessionId.
   */
  long getSessionId();
}
