// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HallLoginMessage.proto

package info.xiaomo.server.shared.protocol.hall.login;

public interface LoginSubGameRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LoginSubGameRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *消息id
   * </pre>
   *
   * <code>optional .MID mid = 1 [default = LoginSubGameReq];</code>
   * @return Whether the mid field is set.
   */
  boolean hasMid();
  /**
   * <pre>
   *消息id
   * </pre>
   *
   * <code>optional .MID mid = 1 [default = LoginSubGameReq];</code>
   * @return The mid.
   */
  info.xiaomo.server.shared.protocol.Mid.MID getMid();

  /**
   * <pre>
   *角色id
   * </pre>
   *
   * <code>required int64 rid = 2;</code>
   * @return Whether the rid field is set.
   */
  boolean hasRid();
  /**
   * <pre>
   *角色id
   * </pre>
   *
   * <code>required int64 rid = 2;</code>
   * @return The rid.
   */
  long getRid();

  /**
   * <pre>
   *类型 0登录，1重连 2跨服登录
   * </pre>
   *
   * <code>optional int32 type = 3;</code>
   * @return Whether the type field is set.
   */
  boolean hasType();
  /**
   * <pre>
   *类型 0登录，1重连 2跨服登录
   * </pre>
   *
   * <code>optional int32 type = 3;</code>
   * @return The type.
   */
  int getType();

  /**
   * <pre>
   *游戏类型 101捕鱼达人
   * </pre>
   *
   * <code>optional int32 gameType = 4;</code>
   * @return Whether the gameType field is set.
   */
  boolean hasGameType();
  /**
   * <pre>
   *游戏类型 101捕鱼达人
   * </pre>
   *
   * <code>optional int32 gameType = 4;</code>
   * @return The gameType.
   */
  int getGameType();
}
