// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HallLoginMessage.proto

package info.xiaomo.server.shared.protocol.hall.login;

/**
 * <pre>
 *登录类型
 * </pre>
 *
 * Protobuf enum {@code LoginType}
 */
public enum LoginType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   *账号登录
   * </pre>
   *
   * <code>ACCOUNT = 1;</code>
   */
  ACCOUNT(1),
  ;

  /**
   * <pre>
   *账号登录
   * </pre>
   *
   * <code>ACCOUNT = 1;</code>
   */
  public static final int ACCOUNT_VALUE = 1;


  public final int getNumber() {
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static LoginType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static LoginType forNumber(int value) {
    switch (value) {
      case 1: return ACCOUNT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<LoginType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      LoginType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<LoginType>() {
          public LoginType findValueByNumber(int number) {
            return LoginType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return info.xiaomo.server.shared.protocol.hall.login.HallLoginMessage.getDescriptor().getEnumTypes().get(0);
  }

  private static final LoginType[] VALUES = values();

  public static LoginType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private LoginType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:LoginType)
}

