// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HallChatMessage.proto

package info.xiaomo.server.shared.protocol.hall.chat;

public interface ChatResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ChatResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *消息id
   * </pre>
   *
   * <code>optional .MID mid = 1 [default = ChatRes];</code>
   * @return Whether the mid field is set.
   */
  boolean hasMid();
  /**
   * <pre>
   *消息id
   * </pre>
   *
   * <code>optional .MID mid = 1 [default = ChatRes];</code>
   * @return The mid.
   */
  info.xiaomo.server.shared.protocol.Mid.MID getMid();

  /**
   * <pre>
   *发送者ID
   * </pre>
   *
   * <code>optional int64 senderId = 2;</code>
   * @return Whether the senderId field is set.
   */
  boolean hasSenderId();
  /**
   * <pre>
   *发送者ID
   * </pre>
   *
   * <code>optional int64 senderId = 2;</code>
   * @return The senderId.
   */
  long getSenderId();

  /**
   * <pre>
   *发送者头像
   * </pre>
   *
   * <code>optional string senderHead = 3;</code>
   * @return Whether the senderHead field is set.
   */
  boolean hasSenderHead();
  /**
   * <pre>
   *发送者头像
   * </pre>
   *
   * <code>optional string senderHead = 3;</code>
   * @return The senderHead.
   */
  java.lang.String getSenderHead();
  /**
   * <pre>
   *发送者头像
   * </pre>
   *
   * <code>optional string senderHead = 3;</code>
   * @return The bytes for senderHead.
   */
  com.google.protobuf.ByteString
      getSenderHeadBytes();

  /**
   * <pre>
   *发送者昵称
   * </pre>
   *
   * <code>optional string senderNick = 4;</code>
   * @return Whether the senderNick field is set.
   */
  boolean hasSenderNick();
  /**
   * <pre>
   *发送者昵称
   * </pre>
   *
   * <code>optional string senderNick = 4;</code>
   * @return The senderNick.
   */
  java.lang.String getSenderNick();
  /**
   * <pre>
   *发送者昵称
   * </pre>
   *
   * <code>optional string senderNick = 4;</code>
   * @return The bytes for senderNick.
   */
  com.google.protobuf.ByteString
      getSenderNickBytes();

  /**
   * <pre>
   *聊天类型
   * </pre>
   *
   * <code>required .ChatType chatType = 5;</code>
   * @return Whether the chatType field is set.
   */
  boolean hasChatType();
  /**
   * <pre>
   *聊天类型
   * </pre>
   *
   * <code>required .ChatType chatType = 5;</code>
   * @return The chatType.
   */
  info.xiaomo.server.shared.protocol.hall.chat.ChatType getChatType();

  /**
   * <pre>
   *聊天消息
   * </pre>
   *
   * <code>optional string msg = 6;</code>
   * @return Whether the msg field is set.
   */
  boolean hasMsg();
  /**
   * <pre>
   *聊天消息
   * </pre>
   *
   * <code>optional string msg = 6;</code>
   * @return The msg.
   */
  java.lang.String getMsg();
  /**
   * <pre>
   *聊天消息
   * </pre>
   *
   * <code>optional string msg = 6;</code>
   * @return The bytes for msg.
   */
  com.google.protobuf.ByteString
      getMsgBytes();
}
