// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HallChatMessage.proto

package info.xiaomo.server.shared.protocol.hall.chat;

public interface ModifyMailRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ModifyMailRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *消息id
   * </pre>
   *
   * <code>optional .MID mid = 1 [default = ModifyMailReq];</code>
   * @return Whether the mid field is set.
   */
  boolean hasMid();
  /**
   * <pre>
   *消息id
   * </pre>
   *
   * <code>optional .MID mid = 1 [default = ModifyMailReq];</code>
   * @return The mid.
   */
  info.xiaomo.server.shared.protocol.Mid.MID getMid();

  /**
   * <pre>
   *邮件ID
   * </pre>
   *
   * <code>required int64 mailId = 2;</code>
   * @return Whether the mailId field is set.
   */
  boolean hasMailId();
  /**
   * <pre>
   *邮件ID
   * </pre>
   *
   * <code>required int64 mailId = 2;</code>
   * @return The mailId.
   */
  long getMailId();

  /**
   * <pre>
   *状态 0新邮件、1已读、2已领取道具、3删除
   * </pre>
   *
   * <code>required int32 state = 3;</code>
   * @return Whether the state field is set.
   */
  boolean hasState();
  /**
   * <pre>
   *状态 0新邮件、1已读、2已领取道具、3删除
   * </pre>
   *
   * <code>required int32 state = 3;</code>
   * @return The state.
   */
  int getState();
}
