// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HallPacketMessage.proto

package info.xiaomo.server.shared.protocol.hall.packet;

public interface UseItemRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UseItemRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *消息id
   * </pre>
   *
   * <code>optional .MID mid = 1 [default = UseItemReq];</code>
   * @return Whether the mid field is set.
   */
  boolean hasMid();
  /**
   * <pre>
   *消息id
   * </pre>
   *
   * <code>optional .MID mid = 1 [default = UseItemReq];</code>
   * @return The mid.
   */
  info.xiaomo.server.shared.protocol.Mid.MID getMid();

  /**
   * <pre>
   *物品ID
   * </pre>
   *
   * <code>required int64 itemId = 2;</code>
   * @return Whether the itemId field is set.
   */
  boolean hasItemId();
  /**
   * <pre>
   *物品ID
   * </pre>
   *
   * <code>required int64 itemId = 2;</code>
   * @return The itemId.
   */
  long getItemId();
}
