// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerMessage.proto

package info.xiaomo.server.shared.protocol.server;

public interface ChangeRoleServerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ChangeRoleServerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .MID mid = 1 [default = ChangeRoleServerReq];</code>
   * @return Whether the mid field is set.
   */
  boolean hasMid();
  /**
   * <code>optional .MID mid = 1 [default = ChangeRoleServerReq];</code>
   * @return The mid.
   */
  info.xiaomo.server.shared.protocol.Mid.MID getMid();

  /**
   * <pre>
   *目标服务器ID
   * </pre>
   *
   * <code>optional int32 serverId = 2;</code>
   * @return Whether the serverId field is set.
   */
  boolean hasServerId();
  /**
   * <pre>
   *目标服务器ID
   * </pre>
   *
   * <code>optional int32 serverId = 2;</code>
   * @return The serverId.
   */
  int getServerId();

  /**
   * <pre>
   *目标服务器类型
   * </pre>
   *
   * <code>required int32 serverType = 3;</code>
   * @return Whether the serverType field is set.
   */
  boolean hasServerType();
  /**
   * <pre>
   *目标服务器类型
   * </pre>
   *
   * <code>required int32 serverType = 3;</code>
   * @return The serverType.
   */
  int getServerType();

  /**
   * <pre>
   *角色ID
   * </pre>
   *
   * <code>required int64 roleId = 4;</code>
   * @return Whether the roleId field is set.
   */
  boolean hasRoleId();
  /**
   * <pre>
   *角色ID
   * </pre>
   *
   * <code>required int64 roleId = 4;</code>
   * @return The roleId.
   */
  long getRoleId();
}
