// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerMessage.proto

package info.xiaomo.server.shared.protocol.server;

public interface ServerEventRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ServerEventRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .MID mid = 1 [default = ServerEventReq];</code>
   * @return Whether the mid field is set.
   */
  boolean hasMid();
  /**
   * <code>optional .MID mid = 1 [default = ServerEventReq];</code>
   * @return The mid.
   */
  info.xiaomo.server.shared.protocol.Mid.MID getMid();

  /**
   * <pre>
   *事件类型  1踢玩家
   * </pre>
   *
   * <code>required int32 type = 2;</code>
   * @return Whether the type field is set.
   */
  boolean hasType();
  /**
   * <pre>
   *事件类型  1踢玩家
   * </pre>
   *
   * <code>required int32 type = 2;</code>
   * @return The type.
   */
  int getType();

  /**
   * <pre>
   *int参数
   * </pre>
   *
   * <code>optional int32 serverId = 3;</code>
   * @return Whether the serverId field is set.
   */
  boolean hasServerId();
  /**
   * <pre>
   *int参数
   * </pre>
   *
   * <code>optional int32 serverId = 3;</code>
   * @return The serverId.
   */
  int getServerId();

  /**
   * <pre>
   *long参数
   * </pre>
   *
   * <code>optional int64 id = 4;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <pre>
   *long参数
   * </pre>
   *
   * <code>optional int64 id = 4;</code>
   * @return The id.
   */
  long getId();

  /**
   * <pre>
   *Id列表
   * </pre>
   *
   * <code>repeated int64 ids = 5;</code>
   * @return A list containing the ids.
   */
  java.util.List<java.lang.Long> getIdsList();
  /**
   * <pre>
   *Id列表
   * </pre>
   *
   * <code>repeated int64 ids = 5;</code>
   * @return The count of ids.
   */
  int getIdsCount();
  /**
   * <pre>
   *Id列表
   * </pre>
   *
   * <code>repeated int64 ids = 5;</code>
   * @param index The index of the element to return.
   * @return The ids at the given index.
   */
  long getIds(int index);

  /**
   * <pre>
   *其他额外信息
   * </pre>
   *
   * <code>optional string info = 6;</code>
   * @return Whether the info field is set.
   */
  boolean hasInfo();
  /**
   * <pre>
   *其他额外信息
   * </pre>
   *
   * <code>optional string info = 6;</code>
   * @return The info.
   */
  java.lang.String getInfo();
  /**
   * <pre>
   *其他额外信息
   * </pre>
   *
   * <code>optional string info = 6;</code>
   * @return The bytes for info.
   */
  com.google.protobuf.ByteString
      getInfoBytes();
}
