// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerMessage.proto

package info.xiaomo.server.shared.protocol.server;

public interface ServerListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ServerListRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .MID mid = 1 [default = ServerListReq];</code>
   * @return Whether the mid field is set.
   */
  boolean hasMid();
  /**
   * <code>optional .MID mid = 1 [default = ServerListReq];</code>
   * @return The mid.
   */
  info.xiaomo.server.shared.protocol.Mid.MID getMid();

  /**
   * <pre>
   *服务器类型
   * </pre>
   *
   * <code>required int32 serverType = 2;</code>
   * @return Whether the serverType field is set.
   */
  boolean hasServerType();
  /**
   * <pre>
   *服务器类型
   * </pre>
   *
   * <code>required int32 serverType = 2;</code>
   * @return The serverType.
   */
  int getServerType();
}
